sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t jeonhs2482/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jeonhs2482/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-eb"
  env: "Docker-react-eb-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-803078395384"
  bucket_path: "docker-react-eb"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
